
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.css" />
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css" />

    <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.js"></script>-->


<?php $productCollection = $block->getcompanyCollection(); ?>
<?php $distinutor = json_encode($block->getCompanyList()); ?>
<?php $distibutor = json_encode($block->getCompanyList1()); ?>
<input type="hidden" data-form-part="product_form" id="distibutorlist"  name="distibutors" value="">
<input type="hidden" data-form-part="product_form" id="saveddistibutorlist"  name="sdistibutors" value="<?php echo $productCollection;?>">



<div id="jsGrid"></div>


<script type="text/javascript">
require(['jquery','//cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.js'],function($){



	     var clients = <?php echo $distinutor;?>;
		 var dclients = <?php echo $distibutor;?>;



    $(document).ready(function() {


	  var datalist=$("#saveddistibutorlist").val();
	  	var array = datalist.split(',');



	    $("#jsGrid").jsGrid({
        width: "100%",
        height: "400px",

        inserting: false,
        editing: false,
		filtering: true,
        sorting: true,
        paging: true,

        data: dclients,

      


         fields: [
            { name: "Name", type: "text", width: 150,title:"Company Name"},
            { name: "Country", type: "text", width: 200 },
            { name: "Type", type: "text", width: 200 ,title:"Company Type"},

            { name: "Orgid",  title: "Select",itemTemplate: function(value, item) {
              	return $("<input>").attr("type", "checkbox")

						.attr("class", 'a-center')
						.val(value)
                    .on("click", function() {
                    	values1 = $('input:checkbox:checked.a-center').map(function () {
                                    return this.value;
                                    }).get();
                                  $("#distibutorlist").val(values1);
								  });

              } },
          ],
         
		 
		controller: {
			data:clients,

            //alert("dssdsd");
 
           loadData: function (filter) {
                 
				console.log(filter);
                return $.grep(this.data, function (item) {
                    return (!filter.Name || item.Name.indexOf(filter.Name)>= 0)

                    && (!filter.Country || item.Country.toLowerCase().indexOf(filter.Country.toLowerCase()) > -1)
                    && (!filter.Type || item.Type.toLowerCase().indexOf(filter.Type.toLowerCase()) > -1)
                    && (!filter.Country || item.Country === filter.Country)

					//return (!filter.Address || item.Address.indexOf(filter.Address) >= 0);

					if($("#distibutorlist").val()!="")
		{
		var selectedlist=$("#distibutorlist").val();
	  	var arraylist = selectedlist.split(',');
		$.each(arraylist, function(index, vals) {

		$('.a-center:checkbox[value="' + vals + '"]').attr('checked', true);

		});
		}
                });
            },
        }

    });




  $('.jsgrid-cell input').keyup(function(){
	  $.each(array, function(index, val) {
		$('.a-center:checkbox[value="' + val + '"]').attr('checked', true);

		});

		if($("#distibutorlist").val()!="")
		{
		var selectedlist=$("#distibutorlist").val();
	  	var arraylist = selectedlist.split(',');
		$.each(arraylist, function(index, vals) {
		$('.a-center:checkbox[value="' + vals + '"]').attr('checked', true);

		});
		}
   });

   $(".jsgrid-header-sortable").click(function(){

	   $.each(array, function(index, val) {
		$('.a-center:checkbox[value="' + val + '"]').attr('checked', true);

		});

		if($("#distibutorlist").val()!="")
		{
		var selectedlist=$("#distibutorlist").val();
	  	var arraylist = selectedlist.split(',');
		$.each(arraylist, function(index, vals) {
		$('.a-center:checkbox[value="' + vals + '"]').attr('checked', true);

		});
		}
   })

   $.each(array, function(index, val) {
		$('.a-center:checkbox[value="' + val + '"]').attr('checked', true);

		});


	  });
});
</script>
