<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<a class="link-copyrights" href="https://diva.netenrich.com/" target="_blank" title="<?php /* @escapeNotVerified */ echo __('NetEnrich eCommerce') ?>"></a>
<?php /* @escapeNotVerified */ echo __('Copyright &copy; %1 NetEnrich eCommerce . All rights reserved.', date('Y')) ?>

