<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<a class="link-copyright" href="https://diva.netenrich.com/" target="_blank" title="<?php /* @escapeNotVerified */ echo __('Diva') ?>"></a>
<?php /* @escapeNotVerified */ echo __('Copyright &copy; %1 Netrich Order Management . All rights reserved.', date('Y')) ?>
